//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaciaBelen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIAPRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATEGORIAPRODUCTO()
        {
            this.SUBCATEGORIAPRODUCTO = new HashSet<SUBCATEGORIAPRODUCTO>();
        }
    
        public string CATEGORIAPRODUCTO_ID { get; set; }
        public string CATEGORIAPRODUCTO_NOMBRE { get; set; }
        public string CATEGORIAPRODUCTO_DESCRIPCION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBCATEGORIAPRODUCTO> SUBCATEGORIAPRODUCTO { get; set; }
    }
}
