//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaciaBelen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLEVENTA
    {
        public int DETALLEVENTA_ID { get; set; }
        public string VENTA_ID { get; set; }
        public int INVENTARIO_ID { get; set; }
        public string PRODUCTO_ID { get; set; }
        public int DETALLEVENTA_CANTIDADVENDIDA { get; set; }
        public decimal DETALLEVENTA_PRECIOUNITARIO { get; set; }
        public decimal DETALLEVENTA_SUBTOTAL { get; set; }
    
        public virtual INVENTARIO_PRODUCTO INVENTARIO_PRODUCTO { get; set; }
        public virtual VENTA VENTA { get; set; }
    }
}
