//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaciaBelen.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBFARMACIABELENEntities : DbContext
    {
        public DBFARMACIABELENEntities()
            : base("name=DBFARMACIABELENEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AREA> AREA { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADO { get; set; }
        public virtual DbSet<PERSONA> PERSONA { get; set; }
        public virtual DbSet<PUESTO> PUESTO { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<CATEGORIAPRODUCTO> CATEGORIAPRODUCTO { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<FORMAFARMACEUTICA> FORMAFARMACEUTICA { get; set; }
        public virtual DbSet<INVENTARIO_PRODUCTO> INVENTARIO_PRODUCTO { get; set; }
        public virtual DbSet<METODOPAGO> METODOPAGO { get; set; }
        public virtual DbSet<MODULO> MODULO { get; set; }
        public virtual DbSet<PEDIDO> PEDIDO { get; set; }
        public virtual DbSet<PERMISOS> PERMISOS { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTO { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<RECIBO> RECIBO { get; set; }
        public virtual DbSet<SUBCATEGORIAPRODUCTO> SUBCATEGORIAPRODUCTO { get; set; }
        public virtual DbSet<VENTA> VENTA { get; set; }
        public virtual DbSet<VIAADMINISTRACION> VIAADMINISTRACION { get; set; }
        public virtual DbSet<DETALLEVENTA> DETALLEVENTA { get; set; }
        public virtual DbSet<DETALLE_PEDIDO> DETALLE_PEDIDO { get; set; }
    }
}
