//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaciaBelen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.INVENTARIO_PRODUCTO = new HashSet<INVENTARIO_PRODUCTO>();
            this.DETALLE_PEDIDO = new HashSet<DETALLE_PEDIDO>();
        }
    
        public string PRODUCTO_ID { get; set; }
        public string PRODUCTO_NOMBRE { get; set; }
        public string PRODUCTO_DESCRIPCION { get; set; }
        public Nullable<System.DateTime> PRODUCTO_FECHACREACION { get; set; }
        public string FORMAFARMACEUTICA_ID { get; set; }
        public string VIAADMINISTRACION_ID { get; set; }
        public string PRODUCTO_CASAMEDICA { get; set; }
        public string PRODUCTO_IMG { get; set; }
        public string PRODUCTO_ESTADO { get; set; }
        public string SUBCATEGORIAPRODUCTO_ID { get; set; }
    
        public virtual FORMAFARMACEUTICA FORMAFARMACEUTICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVENTARIO_PRODUCTO> INVENTARIO_PRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_PEDIDO> DETALLE_PEDIDO { get; set; }
        public virtual SUBCATEGORIAPRODUCTO SUBCATEGORIAPRODUCTO { get; set; }
        public virtual VIAADMINISTRACION VIAADMINISTRACION { get; set; }
    }
}
