//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaciaBelen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECIBO
    {
        public string RECIBO_ID { get; set; }
        public string VENTA_ID { get; set; }
        public string METODOPAGO_ID { get; set; }
    
        public virtual METODOPAGO METODOPAGO { get; set; }
        public virtual VENTA VENTA { get; set; }
    }
}
